import tensorflow as tf
import numpy as np
import cv2 # You will need to install OpenCV: pip install opencv-python-headless

def get_gradcam_heatmap(img_array, model, pred_index=None, last_conv_layer_name='conv2d_3'):
    """
    Computes a Grad-CAM heatmap for a given image, model, and target class.

    Args:
        img_array: Preprocessed image input (shape: 1, 224, 224, 3).
        model: Your loaded Keras model.
        pred_index: The index of the class to target (e.g., the predicted class).
        last_conv_layer_name: The name of the final convolutional layer.
                              (For your Sequential CNN, this is likely 'conv2d_3' or 'conv2d_4').
    
    Returns:
        A numpy array representing the heatmap (224x224).
    """
    
    # 1. Create a model that maps the input image to the activations of the last conv layer
    # and the final output predictions.
    grad_model = tf.keras.models.Model(
        model.inputs, [model.get_layer(last_conv_layer_name).output, model.output]
    )

    # 2. Watch the computation using GradientTape
    with tf.GradientTape() as tape:
        # Get the feature maps and predictions
        last_conv_layer_output, preds = grad_model(img_array)
        
        # If no specific class index is provided, use the highest probability class
        if pred_index is None:
            pred_index = tf.argmax(preds[0])
            
        # Get the loss for the target class
        target_class_channel = preds[:, pred_index]

    # 3. Calculate the gradient of the target class output w.r.t the last conv layer output
    grads = tape.gradient(target_class_channel, last_conv_layer_output)
    
    # 4. Global Average Pooling (GAP) to get weights for each feature map channel
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # 5. Multiply each channel's activation by its calculated importance weight
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # 6. Apply ReLU to keep only positive contributions (important for the prediction)
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    
    # Convert to numpy and resize to original image size (224x224)
    heatmap = heatmap.numpy()
    heatmap = cv2.resize(heatmap, (img_array.shape[1], img_array.shape[2]))
    
    return heatmap

# --- Helper function to overlay the heatmap on the original image ---

def overlay_heatmap(original_img, heatmap):
    """
    Overlays the heatmap onto the original image.

    Args:
        original_img: The original PIL Image object (before preprocessing).
        heatmap: The 2D numpy array heatmap generated by get_gradcam_heatmap.
        
    Returns:
        The resulting image as a base64 string or PIL Image object.
    """
    
    # Convert original image to BGR for OpenCV
    img = np.array(original_img.resize((224, 224)))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    # Rescale heatmap to 0-255 and apply 'COLORMAP_JET'
    heatmap = np.uint8(255 * heatmap)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    # Superimpose the heatmap on the original image
    superimposed_img = cv2.addWeighted(img, 0.6, heatmap, 0.4, 0)
    
    # Encode the image to base64 string for JSON response
    # You'll need to convert it back to RGB or base64 based on your final output format
    
    # For simplicity, let's return the image as a BGR numpy array
    return superimposed_img